name: "Déclaration a11y scan action"
description: "Détecte la présence d'une déclaration d'accessibilité"

inputs:
  url:
    description: "URL à tester"
    required: true
  output:
    description: "Path to output file. defaults to declaration-a11y.json"
    default: "declaration-a11y.json"
outputs:
  url:
    description: "Declaration url"
    value: ${{ steps.get_json.outputs.url }}

runs:
  using: "composite"
  steps:
    - name: Install
      shell: bash
      run: |
        sudo apt-get install -y jq
        cd ${{ github.action_path }}
        yarn
    - name: Get URL HTML
      uses: socialgouv/dashlord-actions/get-html@v1
      with:
        url: ${{ inputs.url }}
        output: result.html
    - id: get_json
      name: Detect declaration a11y
      shell: bash
      run: |
        cd ${{ github.action_path }}
        JSON=$(node index ${{ inputs.url }} ${{ github.workspace }}/result.html)
        URL=$($JSON | jq -r '.declarationUrl')
        echo "url=$URL" >> $GITHUB_OUTPUT
        echo $JSON > ${{ github.workspace }}/${{ inputs.output }}
