name: "Déclaration a11y scan action"
description: "Détecte la présence d'une déclaration d'accessibilité"

inputs:
  url:
    description: "URL à tester"
    required: true
  output:
    description: "Path to output file. defaults to declaration-a11y.json"
    default: "declaration-a11y.json"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install
      shell: bash
      run: |
        cd ${{ github.action_path }}
        yarn
    - name: Get URL HTML
      uses: socialgouv/dashlord-actions/get-html@v1
      with:
        url: ${{ inputs.url }}
        output: result.html
    - name: Detect declaration a11y
      shell: bash
      run: |
        cd ${{ github.action_path }}
        node index ${{ inputs.url }} ${{ github.workspace }}/result.html > ${{ github.workspace }}/${{ inputs.output }}
        cat ${{ github.workspace }}/${{ inputs.output }}
