name: "DashLord init action"
description: "Parse dashlord config files"
inputs:
  url:
    description: "Single url to scan or scan all urls"
    required: false
    default: ""
  tool:
    description: "Tool to run or use all tools"
    default: ""
    required: false
outputs:
  urls:
    description: List of urls to scan as plain text
    value: ${{ steps.init.outputs.urls }}
  sites:
    description: List of sites with repositories and tools to scan as json
    value: ${{ steps.init.outputs.sites }}
  config:
    description: Full dashlord.yaml config
    value: ${{ steps.init.outputs.config }}
runs:
  using: "node12"
  main: "dist/index.js"
