name: "updown init action"
description: "Create missing entries in updown.io"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: "20"
    - shell: bash
      id: fetch
      run: |
        yarn --cwd ${{ github.action_path }}
        node ${{ github.action_path }}/src/index.js
