name: "DashLord report Action"
description: "Generate a dashlord report"

inputs:
  public-url:
    description: "PUBLIC_URL for the build. see https://create-react-app.dev/docs/using-the-public-folder/#adding-assets-outside-of-the-module-system"
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v2
      with:
        node-version: "14"
    - name: Build
      id: build
      shell: bash
      env:
        SKIP_PREFLIGHT_CHECK: "true"
      run: |
        export REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')
        export REPOSITORY_URL=$(echo 'https://github.com/${{ github.repository }}')
        export DASHLORD_REPO_PATH=${{ github.workspace }};
        export NEXT_PUBLIC_BASE_PATH=$([[ -n "${{ inputs.public-url }}" ]] && echo "${{ inputs.public-url }}" || echo "/$REPOSITORY_NAME")

        echo "REPOSITORY_NAME: $REPOSITORY_NAME"
        echo "REPOSITORY_URL: $REPOSITORY_URL"
        echo "DASHLORD_REPO_PATH: $DASHLORD_REPO_PATH"
        echo "NEXT_PUBLIC_BASE_PATH: $NEXT_PUBLIC_BASE_PATH"

        cd ${{ github.action_path }}
        yarn
        # this creates config.json, report.json and trends.json to build the website
        node src
        cd www
        yarn
        CI=false yarn build && yarn export
        # prevent gh-pages jekyll build
        touch out/.nojekyll
        # save report in workspace for artifact
        cp src/report.json ${{ github.workspace }}/report.json
        # save the build for gh-pages publication
        mv out ${{ github.workspace }}/build
