name: "Get URL HTML action"
description: "Get some URL HTML"

inputs:
  url:
    description: URL to save data for
    required: true
  output:
    description: Path to output file
    default: result.html
    required: false
  locale:
    description: Default Playwright context locale
    default: fr-FR
    required: false

runs:
  using: "composite"
  steps:
    - shell: bash
      id: scan
      run: |
        npx pwpr --url=${{ inputs.url }} --load=30000 --locale ${{ inputs.locale }} --output ${{ inputs.output }}
