name: "Get URL HTML action"
description: "Get some URL HTML"

inputs:
  url:
    description: URL to save data for
    required: true
  output:
    description: Path to output file
    default: result.html
    required: false
  locale:
    description: Default Playwright context locale
    default: fr-FR
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v2
      with:
        node-version: "14"
    - shell: bash
      id: scan
      run: |
        cd ${{ github.action_path }}
        yarn
        node index --url=${{ inputs.url }} --load=30000 --locale ${{ inputs.locale }} --output ${{ github.workspace }}/${{ inputs.output }}
