name: "DashLord eco-index action"
description: "Save dashlord results"

inputs:
  url:
    description: URL to check eco-index
    required: true
  output:
    description: "Path to output file. defaults to ecoindex.json"
    default: "ecoindex.json"
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        docker run --name ecoindex ghcr.io/socialgouv/ecoindex-cli:5.4.2 --url=${{ inputs.url }} --no-interaction --export-format json --output-file /code/out.json
        docker cp ecoindex:/code/out.json ${{ github.workspace }}/${{ inputs.output }}
        cat ${{ github.workspace }}/${{ inputs.output }
