name: "Déclaration RGPD scan action"
description: "Détecte la présence de mentions légales et de politiques de confidentialité"

inputs:
  thirdparties:
    description: "Thirdparties action output to analyze trackers"
    required: false
    default: "{}"
  url:
    description: "URL à tester"
    required: true
  output:
    description: "Path to output file. defaults to declaration-rgpd.json"
    default: "declaration-rgpd.json"

runs:
  using: "composite"
  steps:
    - name: Install
      shell: bash
      run: |
        cd ${{ github.action_path }}
        yarn
    - name: Get URL HTML
      uses: socialgouv/dashlord-actions/get-html@v1
      with:
        url: ${{ inputs.url }}
        output: result.html
    - name: Detect declaration rgpd
      shell: bash
      run: |
        cd ${{ github.action_path }}
        THIRDPARTIES=$(echo $THIRDPARTIES | jq -c 'del(.endpoints)')
        THIRDPARTIES_STR="${THIRDPARTIES//'/\'}" # escapes single quotes
        THIRDPARTIES_STR="${THIRDPARTIES//\\"/"}" # remove escaped double quotes
        node index ${{ inputs.url }} ${{ github.workspace }}/result.html "${THIRDPARTIES_STR}" > ${{ github.workspace }}/${{ inputs.output }}
        cat ${{ github.workspace }}/${{ inputs.output }}
      env:
        THIRDPARTIES: "${{ inputs.thirdparties }}"
