name: "Run lighthouse collect action on some url"
description: "Run lighthouse collect on"

inputs:
  url:
    description: URLs to collect data for
    required: true
  language:
    description: ISO-639 language code
    default: fr
    required: false
  collectFlags:
    description: "LHCI flags, see https://github.com/GoogleChrome/lighthouse-ci/blob/main/docs/configuration.md"
    default: "--numberOfRuns=1"
    required: false
  chromeFlags:
    description: "Chrome flags, see https://peter.sh/experiments/chromium-command-line-switches"
    default: "--no-sandbox --disable-dev-shm-usage --headless --user-agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36 - dashlord'"
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: "14"
    - shell: bash
      id: scan
      run: |
        cd ${{ github.action_path }}
        yarn
        export LANGUAGE="${{ inputs.language}}"
        URLS=$(echo ${{ inputs.url }} | sed "s/^/--url=/" | sed "s/,/ --url=/g")
        echo $URLS
        yarn lhci collect "${{ inputs.collectFlags }}" $URLS --settings.chromeFlags="${{ inputs.chromeFlags }} --lang=$LANGUAGE"
        mv .lighthouseci ${{ github.workspace }}/
