name: "DashLord sonarcloud Action"
description: "Extract data from sonarcloud API"

inputs:
  repos:
    description: "Comma separated list of repos to get results for"
    required: true
  output:
    description: "Path to output file. defaults to sonarcloud.json"
    default: "sonarcloud.json"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: "18"
    - name: Install
      shell: bash
      run: |
        yarn
    - name: Fetch data
      shell: bash
      run: |
        yarn fetch "${{ inputs.repos }}" > "${{ inputs.output }}"
