on:
  push:
    branches: ["*"]
    paths:
      - declaration-a11y
  pull_request:
    branches: ["*"]

name: Test declaration-a11y
jobs:
  tests:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd declaration-a11y
          yarn
          yarn test
