on:
  push:
    branches: ["*"]
    paths:
      - declaration-a11y
      - .github/workflows/declaration-a11y.yml

  pull_request:
    branches: ["*"]
    paths:
      - declaration-a11y
      - .github/workflows/declaration-a11y.yml

name: Test declaration-a11y
jobs:
  tests:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd declaration-a11y
          yarn
          yarn test
  tests-action:
    runs-on: ubuntu-latest
    name: declaration-a11y action
    steps:
      - uses: actions/checkout@v3
      - shell: bash
        run: |
          ls -la
      - uses: ./declaration-a11y
        with:
          url: https://labonnealternance.apprentissage.beta.gouv.fr
          output: a11y.json

      - shell: bash
        run: |
          ls -la
          cat a11y.json
          [[ $(cat a11y.json | jq -rc '.mention') == "Accessibilité : non conforme" ]] || (echo "Error: Should mention Accessibilité : non conforme" && exit 1)
