on:
  push:
    branches: ["*"]
    paths:
      - declaration-rgpd
  pull_request:
    branches: ["*"]

name: Test declaration-rgpd
jobs:
  tests:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd declaration-rgpd
          yarn
          yarn test
