on:
  push:
    branches: ["*"]
    paths:
      - get-html/**
      - .github/workflows/get-html.yml
  pull_request:
    branches: ["*"]
    paths:
      - get-html/**
      - .github/workflows/get-html.yml

name: Test get-html action
jobs:
  tests-report:
    runs-on: ubuntu-latest
    name: get-html action
    steps:
      - uses: actions/checkout@v4
      - shell: bash
        run: |
          ls -la
      - uses: ./get-html
        name: test some URL
        with:
          url: https://opentermsarchive.org
          output: result.html
      - shell: bash
        run: |
          cat result.html | grep Accessibilité
      - uses: ./get-html
        name: test user-agent
        with:
          url: https://httpbin.org/user-agent
          output: user-agent.html
      - shell: bash
        run: |
          cat user-agent.html | grep dashlord
