on:
  push:
    branches: ["*"]
    paths:
      - get-html/**
      - .github/workflows/get-html.yml
  pull_request:
    branches: ["*"]

name: Tests get-html action
jobs:
  tests-report:
    runs-on: ubuntu-latest
    name: get-html action
    steps:
      - uses: actions/checkout@v3
      - shell: bash
        run: |
          ls -la
      - uses: ./get-html
        with:
          url: https://opentermsarchive.org
          output: result.html
      - shell: bash
        run: |
          ls -la
          ls -la get-html
          cat result.html
